
data_dir: "data/RoNIN/extracted"
train_list: "data/RoNIN/lists/list_debug.txt"
val_list: "data/RoNIN/lists/list_debug.txt"

window_size: 200
stride: 100
batch_size: 2
lr: 0.0001
epochs: 1

mode: "end2end" # or residual
log_interval: 1
save_interval: 1
num_inference_steps: 2

test_seen_list: "data/RoNIN/lists/list_debug.txt"
test_unseen_list: "data/RoNIN/lists/list_debug.txt"
