# Debug Config
data_dir: "data/RoNIN/extracted"
train_list: "data/RoNIN/lists/list_debug.txt"
val_list: "data/RoNIN/lists/list_debug.txt"

window_size: 200
stride: 100
batch_size: 16
lr: 0.001
epochs: 1

log_interval: 1
save_interval: 1
