# Local Overfit Config (Sanity Check)
data_dir: "data/RoNIN/extracted"
train_list: "data/RoNIN/lists/list_debug.txt"
val_list: "data/RoNIN/lists/list_debug.txt"

window_size: 200
stride: 10
batch_size: 4  # Small batch size
lr: 0.001
epochs: 50

mode: "end2end"
log_interval: 1
save_interval: 10
num_inference_steps: 10
num_workers: 0 # Disable multiprocessing to ensure output visibility
